- name: Load Custom Feeds (DIY1)
        run: |
          chmod +x $DIY_P1_SH
          ./$DIY_P1_SH
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Config & DIY2
        run: |
          [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt
          ../$DIY_P2_SH
          # 这一步会根据我们手动下载的插件自动更新 .config
          make defconfig
