name: Build OpenWrt 24.10 Official Final

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize Space & Swap
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/share/boost
          sudo docker image prune -a -f
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Init Environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depends_ubuntu_2204)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone Source
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Execute DIY-P1
        run: |
          chmod +x $DIY_P1_SH
          ./$DIY_P1_SH

      - name: Update & Install Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Execute DIY-P2
        working-directory: ./openwrt
        run: |
          [ -e ../$CONFIG_FILE ] && cp ../$CONFIG_FILE .config
          chmod +x ../$DIY_P2_SH
          ../$DIY_P2_SH
          make defconfig

      - name: Download & Compile
        working-directory: ./openwrt
        run: |
          make download -j8
          make -j$(nproc) || make -j1 V=s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_v24.10_Final
          path: openwrt/bin/targets/x86/64/*.img.gz
